### ISSUE TITLE
[Roadmap] Short-term goals

### ISSUE THREAD

**Issue by chrisrzhou** [d2cube/d2cube#10]
Keeping a very rough list of short-term roadmap goals.  This issue maybe subject to change.

High pri
- [ ] Update Docs.
- [ ] Abstract `~/db` and `~/api` to their own repos.
- [ ] Snapshot test `~/db`.  Unit test `~/api`.
- [ ] Research and codegen files in `~/db` from source game files.

Lowpri
- [ ] Revisit and improve `uinix` utils and `uinix-ui` bugs uncovered.
- [ ] Set up and preview the UI system knowledge (e.g. via `uinix-ui-system-preview`).
- [ ] Cleanup code and smell e.g. `rollItem`.
- [ ] Implement Bookmarkable URLs.
- [ ] Implement Inventory.
